#!/usr/bin/env python3
"""
bw2ssh — Generate ~/.ssh/config from Bitwarden SSH keys.

Based on the original bw2ssh (ssh-use) by Vexcited, written in Rust.
Original: https://code.vexcited.com/vexcited/ssh-use

Usage:
    bw2ssh # with a valid BW_SESSION environment variable
    bw2ssh --token <session_token>
    bw2ssh --token <session_token> --dry-run

Obtain a session token with:
    export BW_SESSION=$(bw unlock --raw)

Each Bitwarden SSH Key item must have a HOSTS custom field (required).
Optional custom fields: HOSTNAME, USER.

Access to private keys is handled by the Bitwarden SSH agent.
This tool only writes public keys and generates ~/.ssh/config.
"""

__version__ = "1.0.0"

import argparse
import hashlib
import json
import os
import shutil
import subprocess
import sys
import textwrap
from dataclasses import dataclass
from pathlib import Path


# ── Bitwarden ─────────────────────────────────────────────────────────────────

SESSION_HINT = (
    "Your session token may be invalid or expired. Try:\n"
    "\n"
    "  bw logout\n"
    "  bw login\n"
    "  export BW_SESSION=\"$(bw unlock --raw)\"\n"
    "  bw2ssh --token \"$BW_SESSION\""
)


def bw_list_items(token: str) -> list[dict]:
    bw = "bw.cmd" if sys.platform == "win32" else "bw"
    result = subprocess.run(
        [bw, "list", "items", "--session", token, "--nointeraction"],
        capture_output=True, text=True,
    )

    if result.returncode != 0:
        stderr = result.stderr.strip()
        sys.exit(f"✗ bw error: {stderr}\n\n{SESSION_HINT}")

    stdout = result.stdout.strip()
    if not stdout:
        sys.exit(f"✗ bw returned no data.\n\n{SESSION_HINT}")

    try:
        return json.loads(stdout)
    except json.JSONDecodeError as e:
        sys.exit(f"✗ Failed to parse bw output ({e}).\n\n{SESSION_HINT}")


# ── Parsing ───────────────────────────────────────────────────────────────────

def get_field(fields: list[dict] | None, name: str) -> str | None:
    for f in (fields or []):
        if f.get("name", "").lower() == name.lower():
            v = (f.get("value") or "").strip()
            return v or None
    return None


@dataclass
class Entry:
    name:       str
    hosts:      list[str]
    hostname:   str | None
    user:       str | None
    public_key: str
    key_path:   str          # filename only, e.g. bw_2d9c8fd9e861aa68.pub


def parse_entries(items: list[dict]) -> list[Entry]:
    entries = []
    for item in items:
        ssh_key = item.get("sshKey")
        if not ssh_key:
            continue

        public_key = (ssh_key.get("publicKey") or "").strip()
        if not public_key:
            continue

        fields = item.get("fields")
        hosts_raw = get_field(fields, "HOSTS")
        if not hosts_raw:
            continue

        hosts = [h.strip() for h in hosts_raw.split(",") if h.strip()]
        if not hosts:
            continue

        # Filename derived from SHA-256 of the public key (first 16 hex chars),
        # matching the original Rust implementation exactly.
        digest = hashlib.sha256(public_key.encode()).hexdigest()
        key_filename = f"bw_{digest[:16]}.pub"

        entries.append(Entry(
            name       = item.get("name", "unnamed"),
            hosts      = hosts,
            hostname   = get_field(fields, "HOSTNAME"),
            user       = get_field(fields, "USER"),
            public_key = public_key,
            key_path   = key_filename,
        ))
    return entries


# ── Config generation ─────────────────────────────────────────────────────────

HEADER = """\
# THIS FILE HAS BEEN GENERATED BY bw2ssh.
# DO NOT EDIT IT!

Include config.d/*
"""

TAB = "  "


def generate_ssh_config(entries: list[Entry]) -> str:
    blocks = []
    for e in entries:
        lines = [
            f"# {e.name}",
            f"Host {' '.join(e.hosts)}",
        ]
        if e.hostname:
            lines.append(f"{TAB}HostName {e.hostname}")
        if e.user:
            lines.append(f"{TAB}User {e.user}")
        lines.append(f"{TAB}IdentitiesOnly yes")
        lines.append(f"{TAB}IdentityFile ~/.ssh/{e.key_path}")
        blocks.append("\n".join(lines))

    return HEADER + "\n" + "\n\n".join(blocks) + "\n"


# ── Filesystem ────────────────────────────────────────────────────────────────

def delete_previous_configs(ssh_dir: Path) -> None:
    """Remove the generated config and any previously written bw_*.pub files."""
    config_path = ssh_dir / "config"
    if config_path.exists():
        config_path.unlink()

    for f in ssh_dir.iterdir():
        if f.name.startswith("bw_") and f.suffix == ".pub":
            f.unlink()


# ── Main ──────────────────────────────────────────────────────────────────────

def main() -> None:
    parser = argparse.ArgumentParser(
        prog="bw2ssh",
        description="Generate ~/.ssh/config from Bitwarden SSH keys.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=textwrap.dedent("""\
            Workflow
            --------
            1.  bw login                              # one-time
            2.  bw sync                               # pull latest changes
            3.  export BW_SESSION=$(bw unlock --raw)
            4.  bw2ssh --token "$BW_SESSION"
        """),
    )
    parser.add_argument(
        "--token", "-t", default=None, metavar="SESSION_TOKEN",
        help="Bitwarden session token (from `bw unlock --raw`). "
             "Falls back to $BW_SESSION if not provided.",
    )
    parser.add_argument(
        "--dry-run", action="store_true",
        help="Print what would be written without touching any files",
    )
    parser.add_argument(
        "--version", "-v", action="version", version=f"%(prog)s {__version__}",
    )
    args = parser.parse_args()

    if not shutil.which("bw" if sys.platform != "win32" else "bw.cmd"):
        sys.exit("✗ Bitwarden CLI ('bw') not found. "
                 "Install from https://bitwarden.com/help/cli/")

    token = args.token or os.environ.get("BW_SESSION", "").strip()
    if not token:
        sys.exit("✗ No session token provided. Pass --token or export BW_SESSION.")

    ssh_dir = Path(
        os.environ.get("HOME") or os.environ.get("USERPROFILE", "")
    ).expanduser() / ".ssh"

    print("fetching keys...")
    items   = bw_list_items(token)
    entries = parse_entries(items)

    if not entries:
        sys.exit("no keys found")

    print(f"found {len(entries)} key(s)")

    config_content = generate_ssh_config(entries)

    if args.dry_run:
        print("\n── ~/.ssh/config ────────────────────────────────────────────")
        print(config_content, end="")
        print("─────────────────────────────────────────────────────────────")
        print("\nPublic keys that would be written (600):")
        for e in entries:
            print(f"  {ssh_dir / e.key_path}")
        print("\n(dry run — nothing written)")
        return

    ssh_dir.mkdir(mode=0o700, parents=True, exist_ok=True)
    delete_previous_configs(ssh_dir)

    # Write public keys (600 - readable only by owner)
    for e in entries:
        key_path = ssh_dir / e.key_path
        key_path.write_text(e.public_key + "\n")
        key_path.chmod(0o600)

    # Write config (600)
    config_path = ssh_dir / "config"
    config_path.write_text(config_content)
    config_path.chmod(0o600)

    print(f"wrote {config_path} for the following keys:")
    for e in entries:
        print(f"  - {e.name}")


if __name__ == "__main__":
    main()